#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2015-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys
import pprint

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

...  # Python 3 is required

ap = argparse.ArgumentParser()
ap.add_argument('path', metavar='FILE', nargs='?', help='TOML file to parse')
options = ap.parse_args()
if options.path is not None:
    fp = open(options.path, 'rb')
else:
    fp = sys.stdin.buffer
with fp:
    d = tomllib.load(fp)
pprint.pprint(d)

# vim:ts=4 sts=4 sw=4 et
