#!/usr/bin/python3

# Copyright © 2015-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys
import pprint

import yaml

ap = argparse.ArgumentParser()
ap.add_argument('path', metavar='FILE', nargs='?', help='YAML file to parse')
options = ap.parse_args()
if options.path is not None:
    fp = open(options.path, 'rb')
else:
    fp = sys.stdin.buffer
with fp:
    d = yaml.safe_load(fp)
pprint.pprint(d)

# vim:ts=4 sts=4 sw=4 et
