#!/usr/bin/python3

# Copyright © 2015-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys
import pprint

import yaml

d = yaml.safe_load(sys.stdin)
pprint.pprint(d)

# vim:ts=4 sts=4 sw=4 et
